### ISSUE TITLE
Cool project!

### ISSUE THREAD

**Issue by ijcd** [vic/macpato#1]
Thanks for writing this. :)

**Comment by vic** [comment]
Haha, glad you like it, it's just a toy, I've made some other experiments using Elixir macros. I tend to enjoy a lot exploring how much I can do with the language syntax.

Cheers !

**Comment by vic** [comment]
And .. actually, if you look at the history this was the predecesor of my current [Expat](http://github.com/vic/expat) project that just reached v1.0 :)

**Comment by ijcd** [comment]
Sweet. That looks nice too. :)
